// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvfzokwcyetfjawpupmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2Znpva3djeWV0Zmphd3B1cG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjkwNjksImV4cCI6MjA2MDEwNTA2OX0.PGzKnOzmyAHXN4wGes6wU_KzrrgiJgxFbNe6UEbeeSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);